### ISSUE TITLE
Multi-selection: TAB action should advance to next?

### ISSUE THREAD

**Issue by knightpp** [koki-develop/go-fzf#54]
When using `WithNoLimit(true)` to show the UI, TAB action is to select/deselect an item. Should TAB select the next item automatically? It makes sense when you need to select multiple consecutive items. I'd like to implement that, but should it be configurable or hardcoded?

**Comment by koki-develop** [comment]
> Should TAB select the next item automatically? It makes sense when you need to select multiple consecutive items.

I think it should.

> I'd like to implement that, but should it be configurable or hardcoded?

Thank you very much!
I think a hard code is sufficient 👍
